### ISSUE TITLE
elfinder shows as Full page without the admin theme 

### ISSUE THREAD

**Issue by mansourcodes** [Laravel-Backpack/FileManager#13]
The file manager menu item leads to a full-page 
without the admin theme.

it's work fine as popup page in the NewsCRUD, but as stand alone it shows as this: 

<img width="1440" alt="Screen Shot 2020-12-20 at 3 32 33 PM" src="https://user-images.githubusercontent.com/3064487/102713342-af848980-42d8-11eb-90a9-cf063e6f44bf.png">

I think it's because I copied the resources/views from Barryvdh\Elfinde
`php artisan vendor:publish --provider='Barryvdh\Elfinder\ElfinderServiceProvider' --tag=views`

what is the current command to copy the views from FileManager

**Comment by mansourcodes** [comment]
## Solved
using those commands after installing `Backpack\FileManager`

### publish views 
`php artisan vendor:publish --provider='Backpack\FileManager\FileManagerServiceProvider' --tag=views`

### publish config 
` php artisan vendor:publish --provider='Backpack\FileManager\FileManagerServiceProvider' --tag=config`

### publish public css file 
`php artisan vendor:publish --provider='Backpack\FileManager\FileManagerServiceProvider' --tag=public`

**Comment by de-raaf-media** [comment]
Thanks @mansourcodes
