### ISSUE TITLE
Incorrect path

### ISSUE THREAD

**Issue by kak2z7702** [Laravel-Backpack/FileManager#16]
Hey.
I ask for help, I can not solve the problem.

1. I have S3 storage.
2. I upload the file test.txt to the root of S3 storage
3. I get the path /s3/test.txt
4. I save to db "/s3/test.txt"
5. I create a link to a file (Storage::url()) "https://s3.****************/s3/test.txt"
6. But my file is in the root of the storage "https://s3.****************/test.txt"
7. How to remove "/s3" from the path to the file that is saving to the database?
Thank you.

**Comment by adzon** [comment]
> Hey.
> I ask for help, I can not solve the problem.
> 
> 1. I have S3 storage.
> 2. I upload the file test.txt to the root of S3 storage
> 3. I get the path /s3/test.txt
> 4. I save to db "/s3/test.txt"
> 5. I create a link to a file (Storage::url()) "https://s3.****************/s3/test.txt"
> 6. But my file is in the root of the storage "https://s3.****************/test.txt"
> 7. How to remove "/s3" from the path to the file that is saving to the database?
>    Thank you.

Have you fixed it?

**Comment by promatik** [comment]
Hi @adzon, do you have the same problem?

**Comment by promatik** [comment]
Hi @kak2z7702, hi @adzon!

I was trying to understand where do you guys upload the file, do you use the upload field and `\Storage::put/move`?
Or do you use the File Manager?

Can you describe the 3rd step? From where do you get the path?
Thanks!

**Comment by promatik** [comment]
Hi everyone!
Since it's been a long time with no updates, I'll close this issue for now, please re-open if this is really an issue in FileManager ✌
