### ISSUE TITLE
Improvement on `install` command

### ISSUE THREAD

**Issue by jiaojie1989** [Laravel-Backpack/FileManager#19]
In file https://github.com/Laravel-Backpack/FileManager/blob/master/src/Console/Commands/Install.php line 59
```
        $this->line(' Publishing elFinder assets');
        $this->executeProcess(['php', 'artisan', 'elfinder:publish']);
```

It's better use `executeArtisanProcess` instead of `executeProcess`, for there exists differences between environments of users, the command `php` may refer to another bin file than the running one.

Improvement:
```
        $this->executeArtisanProcess('elfinder:publish');
```

**Comment by promatik** [comment]
Thank you for the heads up @jiaojie1989 🙌

I've integrated that change on https://github.com/Laravel-Backpack/FileManager/pull/25/files#diff-5edc8f1b571acbaf0d8d72484f20e346177a145de58e48e1f354ba786bf2574fR59
