### ISSUE TITLE
support for Azure storage or AWS S3 

### ISSUE THREAD

**Issue by webdesign7** [Laravel-Backpack/FileManager#2]
I wonder if there is support to store files on a cloud like AWS S3 or / Azure Storage rather then local ?  If not .. can you provide an advise where to start looking . Thanks

**Comment by promatik** [comment]
Hi @webdesign7 sorry for taking so long to answer.

Yes, there is support to store files on the cloud, I use this to store files on Digital Ocean for instance which has an API similar to AWS.
You just need to set `FILESYSTEM_DRIVER="s3"` on you `.env`.

**Comment by masoudjahromi** [comment]
@webdesign7 you need to modify `elfinder.php`

```
    'disks' => [
        's3', // or whatever your disk name is
    ],

```
