### ISSUE TITLE
Add Laravel 9 support to FileManager

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/FileManager#20]
Also mentioned in https://github.com/Laravel-Backpack/demo/pull/342#issuecomment-1016241251 

In order for this package to get L9 support... [barryvdh/laravel-elfinder](https://github.com/barryvdh/laravel-elfinder) needs to provide L9 support, so it needs an upgrade for [league/flysystem](https://github.com/thephpleague/flysystem), from v1 to v3 ([what Laravel 9 uses](https://laravel.com/docs/master/upgrade#flysystem-3)).

**Comment by tabacitu** [comment]
@pxpm I've decided this is too big for me. If I start doing this... I won't get [my other MUSTs for 4.2](https://github.com/orgs/Laravel-Backpack/projects/3?card_filter_query=label%3A%22priority%3A+must%22) done, until Tuesday. 

If you finish everything else assigned to you in [the 4.2 MUSTs board](https://github.com/orgs/Laravel-Backpack/projects/3?card_filter_query=label%3A%22priority%3A+must%22), you can also take this on. But _only if_ everything else is done and finished and we're happy with 4.2! We should keep in mind that is an add-on, and only 16% of all people using Backpack use FileManager. We gotta focus on the 84% first.

**Comment by guleswine** [comment]
how i can see [laravel-elfinder](https://github.com/barryvdh/laravel-elfinder) update dependency "league/flysystem": "^1.0|^3.0",

**Comment by pxpm** [comment]
Hello @guleswine indeed the code is there, but it's not tagged yet. Lastest release is 0.4.7 still.

**Comment by tabacitu** [comment]
**Heads-up guys:** I do NOT expect it to be as easy as that. I think some structural changes are needed in its dependency, `barryvdh/elfinder-flysystem-driver`. I've asked @promatik to take a closer look and he thinks the same way. And I see there's already https://github.com/barryvdh/elfinder-flysystem-driver/pull/83#issuecomment-1055289670 trying to add support to it, but not without problems.

@promatik will take another look, maybe there's a way we can help push this forward and help Barry. But it might take a few weeks to add L9 support to this, so please plan accordingly.

**Comment by tabacitu** [comment]
Fixed in https://github.com/Laravel-Backpack/FileManager/pull/22
