### ISSUE TITLE
Not working with octane roadrunner

### ISSUE THREAD

**Issue by masrodjie** [Laravel-Backpack/FileManager#27]
The issue is might came from https://github.com/barryvdh/laravel-elfinder or https://github.com/Studio-42/elFinder/ since the package has dependencies with them. When trying to use octane roadrunner, it show error message box:

`Unknown command.`

And it's stop working.

**Comment by pxpm** [comment]
Hey @masrodjie thanks for raising the issue. 
I've never tried roadrunner (only swoole), not sure if it has the same problem. 

There isn't a way to get a more descriptive error log ? `-vvv` or something ?

Cheers

**Comment by jorgetwgroup** [comment]
Thank you for bringing up the issue with regards to the compatibility of our current setup with RoadRunner. Unfortunately, at this moment, we haven't fully covered support for RoadRunner. However, I want to assure you that we are actively working towards making it fully compatible in the future.

Upon investigating the problem, it appears that the issue may be stemming from the dependencies of the package you mentioned: https://github.com/barryvdh/laravel-elfinder and https://github.com/Studio-42/elFinder/. It seems that when attempting to use Octane RoadRunner, an error message box appears, displaying the message "Unknown command," which subsequently causes the system to stop working.

To address this issue, we will thoroughly examine the dependencies and evaluate potential solutions. Our team is dedicated to resolving compatibility problems and providing a seamless experience for our users. We appreciate your understanding and patience in this matter.

If you have any additional information or insights regarding the issue, please feel free to share them with us. We value your feedback and involvement in improving our system.

Thank you once again for bringing this to our attention, and we will keep you updated on any progress made towards achieving full compatibility with RoadRunner.

Best regards

**Comment by tjslash** [comment]
@jcastroa87 
any news?
