### ISSUE TITLE
Add support for BackPack v6

### ISSUE THREAD

**Issue by jnoordsij** [Laravel-Backpack/FileManager#28]
Encountered while testing out the new v6 beta. Currently no version (including the `6.x-dev` version) supports the new v6 beta. It would be nice to have a v6-compatible version for testing this when running the beta, to ensure everything works fine ;)

**Comment by tabacitu** [comment]
Just pushed a fix to https://github.com/Laravel-Backpack/FileManager/pull/26 so that you can use that branch in v6. So you should be able to do `composer require backpack/filemanager:"v6.x-dev"` and get the branch with v6 support.

**Comment by de-raaf-media** [comment]
Hi @tabacitu, is the filemanager not ready for production yet? I installed the 6.x-dev version and now get an error:

No hint path defined for [backpack].

This was all working. Just upgraded to Laravel 10 and Backpack 6.

**Comment by de-raaf-media** [comment]
And of course moments later I got it to work. I decided to compare the blade views. The filemanager install command does not override existing views apparently. Deleting the views and then execute filemanager installation works fine. So problem solved. Just an issue where the sidebar menu item is not added.

**Comment by tabacitu** [comment]
Hmmm right, I've just added an Upgrade section to the README. Thanks @de-raaf-media 

https://github.com/Laravel-Backpack/FileManager/commit/e5207ee098470db74b10670d5b84984a8523fd44
