### ISSUE TITLE
FileManager Composer Install `add-sidebar-content`

### ISSUE THREAD

**Issue by treckstar** [Laravel-Backpack/FileManager#30]
Installation ends with an error due to `add-sidebar-content` not existing anymore.

#29 fix: replace `add-sidebar-content`

<img width="1404" alt="Screenshot 2023-07-02 at 3 41 23 PM" src="https://github.com/Laravel-Backpack/FileManager/assets/2318343/52c3f2ee-d578-4d07-938a-0e9dd712b7d8">

**Comment by tabacitu** [comment]
Thanks for reporting and fixing this @treckstar 🙏
Really appreciate it.
