### ISSUE TITLE
I'm get the error "Cannot create phar '/tmp/TzQTdO', file extension (or combination) not recognised or the directory does not exist"

### ISSUE THREAD

**Issue by krittidet** [Laravel-Backpack/FileManager#34]
Laravel 10.10
PHP 8.2
Backpack 6

I'm fresh install backpack6 and install FileManager Extension, but I'm get the error on below.

![image](https://github.com/Laravel-Backpack/FileManager/assets/61466274/f28b14a3-bb4f-4221-87d9-019228bfa8f5)

![image](https://github.com/Laravel-Backpack/FileManager/assets/61466274/a28116eb-16eb-489a-9469-52b484e4fef4)

**Comment by phpfour** [comment]
Hey @krittidet @marechenok,

Thanks for reporting the issue – we are working on it. I'll update here once we roll out a fix.

Thanks

**Comment by tabacitu** [comment]
@krittidet the team has just merged the fix and released the new version. So a `composer update` should get all the latest versions for you, and have this fixed. Let us know if that's not the case and we'll reopen.

Thanks for bringing this up, btw 🙏
Cheers!

**Comment by marechenok** [comment]
Works great!

**Comment by krittidet** [comment]
That works! 
Thank you.
