### ISSUE TITLE
Doesn't seem to work with Tabler theme in v6

### ISSUE THREAD

**Issue by adrienne** [Laravel-Backpack/FileManager#36]
I am on CRUD (and PRO) v6, and FileManager v3.0.2, and I did re-run the `php artisan backpack:filemanager:install` command. Despite which, in the Tabler theme I am consistently getting this error: 

![image](https://github.com/Laravel-Backpack/FileManager/assets/89705/9e8d7c72-a76c-4b1d-b8b1-b44dabe849cf)

Could use some advice, @tabacitu !

**Comment by pxpm** [comment]
Hey @adrienne before running the install command again, you need to make sure you remove first the older files from `resources/views` folder. 

Cheers

**Comment by adrienne** [comment]
Aha! That worked!

**Comment by pxpm** [comment]
Closing, let me know if you have other issues 🙏
