### ISSUE TITLE
`php artisan backpack:filemanager:install --force` 

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/FileManager#38]
Any chance we can bundle the delete&copy of the blade files into one command, something like `php artisan backpack:filemanager:install --force`?

_Originally posted by @tabacitu in https://github.com/Laravel-Backpack/FileManager/issues/35#issuecomment-1661699763_

**Comment by promatik** [comment]
Fixed with https://github.com/Laravel-Backpack/FileManager/pull/53.
