### ISSUE TITLE
Missing Icons/Font

### ISSUE THREAD

**Issue by arb362** [Laravel-Backpack/FileManager#43]
**Problem**
elFinder Material Theme recently updated to v3.0.0 and in doing so they moved the font from the icons subfolder to the font folder.

![image](https://github.com/Laravel-Backpack/FileManager/assets/6188411/1e094f03-e92f-4ac2-90a9-0b4639cd0f27)
See this [commit](https://github.com/RobiNN1/elFinder-Material-Theme/commit/1e3270234490868b046afc6bac1ff3b9225b4c2e#diff-1e6182f244dc38eacfb5179bd4a6be7772ab17e040b1a9bab1419787ccb8d6d4)
As a result when basset caches everything it misses this and you receive a 404 error and no icons.

**Solution**
The [common_styles.blade](resources/views/common_styles.blade.php) will need updated. 

Oddly enough, Basset still caches the font file from jsdelivr. I'm assuming that because there is not a specific version specified in the url jsdelivr serves up the last version that has that file?

**Comment by rk** [comment]
I can confirm that we are also affected by this issue.

Maybe the specific version should be pinned on these assets and manually checked/updated in the theme? This would prevent breaking changes from going untested.

**Comment by karandatwani92** [comment]
Discussion continued on the [PR](https://github.com/Laravel-Backpack/FileManager/pull/44).
