### ISSUE TITLE
changing File Manager to Files

### ISSUE THREAD

**Issue by prescriptionlifeline** [Laravel-Backpack/FileManager#51]
In all the blade templates there's `trans('backpack::crud.file_manager')`, which is showing up as `File Manager`. I'd lik to change that to `Files`. To that end I could change the appropriate entry in `vendor/backpack/crud/src/resources/lang/en/crud.php` but I'd rather not since any changes I do in `vendor/` will be blown away if I do `composer update` and, since that directory is in my .gitignore wouldn't be shared with anyone else anyway.

Consequently, I thought that if I copied that file to my `resources/` directory that that'd do the trick but it is unclear to me where I'd copy that file. I tried a number of places without success. Here's a non comprehensive list of the directories I tried copying it to:

- `resources/lang/vendor/backpack/crud/en/crud.php`
- `resources/lang/en/vendor/backpack/crud/crud.php`

Any ideas?

**Comment by jcastroa87** [comment]
Hello @prescriptionlifeline 

The correct path to replace lang is

```
lang/vendor/backpack/en/crud.php
```

So you need to copy the language file there and change as you need.

Cheers.

**Comment by jcastroa87** [comment]
Hello.

Due to not activity, I will close this issue; please feel free to re-open or create a new one if needed.

Cheers.
