### ISSUE TITLE
Elfinder should update to new version

### ISSUE THREAD

**Issue by dauvray** [Laravel-Backpack/FileManager#54]
hello,

from elfinder : WARNING: IF YOU HAVE OLDER (IN PARTICULAR 2.1.62 OR EARLIER) VERSIONS OF ELFINDER ON PUBLIC SERVERS, IT MAY CAUSE SERIOUS DAMAGE TO YOUR SERVER AND VISITED USER. YOU SHOULD UPDATE TO THE LATEST VERSION OR REMOVE IT FROM THE SERVER.

in package :

        {{-- elFinder JS (REQUIRED) --}}
        @bassetArchive('https://github.com/Studio-42/elFinder/archive/refs/tags/2.1.62.tar.gz', 'elfinder-2.1.62')
        @basset('elfinder-2.1.62/elFinder-2.1.62/js/elfinder.min.js')

        {{-- elFinder translation (OPTIONAL) --}}
        @if($locale)
        @basset('https://cdnjs.cloudflare.com/ajax/libs/elfinder/2.1.62/js/i18n/elfinder.'.$locale.'.min.js')
        @endif

**Comment by pxpm** [comment]
This was done in the latest release.

Thanks for the headup @dauvray 🙏 

Cheers
