### ISSUE TITLE
ElFinder callback error

### ISSUE THREAD

**Issue by maganius** [Laravel-Backpack/FileManager#6]
I just install backpack in a fresh installation, but when I try use browse_multiple it throws an exception

```
Error in `getFileCallback`.
window.parent.processSelectedFile is not a function
```

This exception is thrown after I select a file.

https://imgur.com/a/QgAYKrf

**Comment by tabacitu** [comment]
Also, if you use the File Manager interface separately from the browse_multiple button - as instructed in the package readme, at `yourapp/admin/elfinder`, do you get the same problem?

**Comment by maganius** [comment]
The problem was  I missed execute this line "php artisan backpack: filemanager:install" maybe in the documentation instead of just mentioning how to install the library, maybe its best to create a link to the direct repository to see the correct installation of this. https://backpackforlaravel.com/docs/4.1/crud-fields#browse_multiple. thanks you tabacitu.
