### ISSUE TITLE
Access forbidden on BackpackElfinderController->showPopup() (browse Crud Field)

### ISSUE THREAD

**Issue by filcius** [Laravel-Backpack/FileManager#65]
I am still using Backpack 5.0 and "backpack/pro" 1.1.3, but I doubt that would change anything.

After updating to filemanager 2.0.2, the Crud Field _browse_ type popup generates a 403 http error. This error is generated by BackpackElfinderController->showPopup(), even if the mime type is not submitted in the query.

Is the mime type required in /elfinder/popup/image request? How do we configure it? 

The Crud form:
![image](https://github.com/user-attachments/assets/45b3b30b-2792-448f-a069-10ffc62dcb40)

The broken file browser popup:
![image](https://github.com/user-attachments/assets/4b2faf38-185f-488e-8e92-53029cfbe634)

The error in the log file : _staging.ERROR: Someone attempted to tamper with mime types in elfinder popup. The attempt was blocked._

If the mime type is indeed optional, I temporarily changed my version of BackpackElfinderController->showPopup like this. Remember, this is for 2.0.2

```
  public function showPopup($input_id)
    {
        $mimes = request('mimes');

        if (isset($mimes)) {
            try {
                $mimes = Crypt::decrypt(urldecode(request('mimes')));
            } catch (\Illuminate\Contracts\Encryption\DecryptException $e) {
                Log::error('Someone attempted to tamper with mime types in elfinder popup. The attempt was blocked.');
                abort(403, 'Unauthorized action.');
            }
            request()->merge(['mimes' => urlencode(serialize($mimes))]);
        }

        if (!empty($mimes)) {
            request()->merge(['mimes' => urlencode(serialize($mimes))]);
        } else {
            request()->merge(['mimes' => '']);
        }

        return $this->app['view']
            ->make($this->package . '::standalonepopup')
            ->with($this->getViewVars())
            ->with(compact('input_id'));
    }
```

**Comment by filcius** [comment]
The bot seems to have useful insight, let me try it.

**Comment by filcius** [comment]
I tried some solutions without success. I keep my issue open.

**Comment by JVariance** [comment]
We're also getting this error

**Comment by pxpm** [comment]
Please see the following thread for solutions: https://github.com/Laravel-Backpack/FileManager/issues/59#issuecomment-2483361147

**Comment by filcius** [comment]
That worked perfectly, thank you. I agree that my issue is a duplicate and a secure solution has been found.

However, I wonder if allowing BackpackElfinderController->showPopup() to receive no mimes query would be secure and leave browse.blade.php untouched. I don't expect change, I just want to point it out for future considerations.

**Comment by pxpm** [comment]
Hello @filcius thanks for getting back after solving your issue 👍 

To answer your question, it's not secure. Imagine the following scenario if we accepted no mimes in the query:
You setup the mimes only to jpg. Me, an attacker, remove the mimes from the query. 
The `showPopup` endpoint would think you set up the field with no mimes, when in the reality it was the attacker who removed the mimes. 

Ensuring that the mimes are always set and encrypted (even if they are empty) prevents an attacker from not sending them (manually removing them from the request) and accessing stuff he shouldn't be able to otherwise. 

We wouldn't need this solution if the `showPopup` enpoint were part of an operation, as in that case we could just get the mimes from the field you setup. But at the time this package was developed we weren't using operations yet, so it works slightly different from our most recent packages. 

Hope it clarifies the things a bit. 👍 

Cheers

**Comment by pxpm** [comment]
> @pxpm Ok, the key argument is that the mime type is encrypted, even if empty. Correct me if I am wrong, does that mean that using the browse field with an empty mime, would cause my endpoint to be insecure?

Insecure only in the "viewing" process. So if you set the mime types to jpg, an user would only be able to see `.jpg` files. If they removed the mimes from the url they would be able to see any type of files that there are in the upload folder, eg, gifs or pngs. 
For uploading files there is a different setting on the config options where you can allow/deny certain file types, and those are not exposed in the url like the "view mimes", so not vulnerable. 

Hope it clarifies it. Let me know if you have other questions 👍

**Comment by diereysaa** [comment]
Sorry to revive this thread but I'm getting the same error as the OP:

When I try to open the gallery on my project, it shows a 403 with the main project window:
![image](https://github.com/user-attachments/assets/90fb2e16-ce90-40b8-8adf-b25e2debb3ac)

The HTTP request is 
https://***/admin/elfinder/popup/featured_image_select and that returns a 403.

Also, we're seeing
```
[2025-01-15 19:55:34] staging.ERROR: Someone attempted to tamper with mime types in elfinder popup. The attempt was blocked.
```
on the logs.

We have the latest backpack versions on the server:
```
backpack/basset                               1.3.6   Dead-simple way to load CSS or JS assets only once per page, when using Laravel 10+.
backpack/crud                                 6.7.47  Quickly build admin interfaces using Laravel, Bootstrap and JavaScript.
backpack/filemanager                          3.0.10  Backpack admin interface for files and folder, using elFinder
backpack/generators                           4.0.7   Generate files for laravel projects
backpack/permissionmanager                    7.2.1   Users and permissions management interface for Laravel 5 using Backpack CRUD.
backpack/pro                                  2.2.31  Operations, Fields, Columns, Filters and Widgets for not-so-simple admin panels.
backpack/theme-coreuiv4                       1.1.5   UI for Backpack v6 that uses CoreUI v4 and Bootstrap v5.
backpack/theme-tabler                         1.2.17  UI for Backpack v6 that uses Tabler and Bootstrap v5.
```

Could it be a folders permission issue?

I think it's important to mention that our project is using laravel multidomain as well (gecche/laravel-multidomain                    11.1)

Thanks in advance.

**Comment by filcius** [comment]
@diereysaa Did you try this? It worked for me.

https://github.com/Laravel-Backpack/FileManager/issues/59#issuecomment-2483361147

**Comment by krittidet** [comment]
Downgrade backpack/filemanager to 3.0.8 it working for me
`composer require backpack/filemanager=3.0.8`
