### ISSUE TITLE
Do not show all the uploaded images from s3

### ISSUE THREAD

**Issue by ShekharKokate** [Laravel-Backpack/FileManager#9]
Hi,
Is it possible, do not show all the images?
Actually problem is that. I have uploaded all the images on amazon s3 and when fetch on file manager, it is taking too much time to load it. Is it possible to show some images and on scroll display images according to limit?

**Comment by promatik** [comment]
Hi @ShekharKokate I think that is not possible at the moment.

The AWS S3 API has an option to list files with an offset, but I think https://github.com/barryvdh/laravel-elfinder haven't implemented that.

Anyway, you should address this issue on [barryvdh/laravel-elfinder](https://github.com/barryvdh/laravel-elfinder), this is something that runs out of backpack scope.

Please correct me if you found a way to do that 🙌
I'll close this issue for now, regards!
